### PR TITLE
Start 3.6.0 release

### PR DESCRIPTION
**Pull request by marcopeereboom**
It worked so well to have a release branch last time so I made a new one.

Let's pile stuff in here and whenever we are convinced we have enough we'll hit release..

### CODE REVIEW

**Comment by LordReg** [comment]
Yeah, it's nice to prepare on the side first and merge in any PRs, etc.

Want to push a patch release first if you have no objection.

**Comment by marcopeereboom** [comment]
Want me to push a 3.5.1 tag?

**Comment by LordReg** [comment]
Still need to add the release info to the `CHANGELOG.md` file so its better to not push the release script tag. Need to create a tag on the final release commit to be able to select it when creating the GitHub release. I'll go ahead and do the same as last time.

**Comment by marcopeereboom** [comment]
Any news on the patch release?

**Comment by LordReg** [comment]
Done :tada: https://github.com/conformal/spectrwm/releases/tag/SPECTRWM_3_5_1

**Comment by marcopeereboom** [comment]
Awesome. So I can use that as the new 3.6.0 base?

**Comment by marcopeereboom** [comment]
anything yall?

**Comment by LordReg** [comment]
pushed rebase to the latest fixes along with the first new feature :smiley:

**Comment by marcopeereboom** [comment]
wheee!!!

**Comment by marcopeereboom** [comment]
So are we ready for a release?

**Comment by marcopeereboom** [comment]
bump

**Comment by LordReg** [comment]
Yeah, nearly there

**Comment by marcopeereboom** [comment]
Ah good find!

Ok @LordReg comment on this PR when ready.

**Comment by marcopeereboom** [comment]
Was that it @LordReg?

**Comment by LordReg** [comment]
@marcopeereboom not quite, fixing the Steam issue

**Comment by LordReg** [comment]
@wavexx Nice catch, fixed

**Comment by marcopeereboom** [comment]
How we doing guys? Ready for a release yet?

**Comment by wavexx** [comment]
The only thing I noticed so far is that sometimes menus from qt5's menu bar stop showing up (hard to say if they stay under the main window or show in some invisible region). It seems that once the main window gets into this state, it stays that way until you restart spectrwm (while keeping the program active). Toggling float on the window or changing workspace layout doesn't change anything.

However it's rare, and I couldn't find a way to reproduce it reliably. I just noticed this on some programs that I was using and all are using qt5 (just speculation - might be general).

**Comment by LordReg** [comment]
@wavexx Should be fixed. I believe the issue you experienced has to do with the way Qt handles _NET_WORKAREA. It only looks at the geometry of the first entry in the list (i.e. ws1). It will position its menu window within that boundary. So the issue would occur if ws1 is/was on a different region.

**Comment by LordReg** [comment]
@marcopeereboom Ready

**Pull request merged**
