### PR TITLE
Update to latest pledge(2).

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by dajohi** [comment]
@bket care to review?

**Comment by bket** [comment]
Pledge bits in `spectrwm.c` are OK.

The change in `Makefile` is not related to `pledge(2)`. In OpenBSD `-lxcb` is added explicitly to `LDADD` as newer linkers don't follow NEEDED. It fixes linking with LLD (https://github.com/openbsd/ports/commit/5290d4fa30cfc9bca8be046fc2e3687485561859#diff-a274454b39210e89e6205aff1bd8e5bf).

What do you think of making a separate commit of the latter?

**Comment by dajohi** [comment]
Sure.  Can you review #218 as well possibly? :)

**Comment by marcopeereboom** [comment]
Doesn't build on non pledge platforms like OSX. You need to stub pledge.
```
[master]$ make
cc -std=c99 -Wmissing-prototypes -Wall -Wextra -Wshadow -Wno-uninitialized -g -O2 -D_GNU_SOURCE -D__OSX__ -I. -I.. -I/opt/X11/include -I/opt/X11/include/freetype2/ -DSWM_LIB=\"/usr/local/lib/libswmhack.so.0.0\" -DSPECTRWM_BUILDSTR=\"eaf5169b0768cba1c46c2be62841e3940e759a25\"   -c -o spectrwm.o spectrwm.c
spectrwm.c:60:10: fatal error: 'pledge.h' file not found
#include "pledge.h"
         ^~~~~~~~~~
1 error generated.
make: *** [spectrwm.o] Error 1
```

**Pull request merged**
