### PR TITLE
Added support for multi-aligned status bar, and updated man-page accordingly

### PR DESCRIPTION
**Pull request by cthelight**
Added the feature of allowing part of the status bar to be left justified and leave the rest right justified.

Also modified the man page to indicate the change.

### CODE REVIEW

**Comment by bket** [comment]
@cthelight, your PR not only adds a new feature but also removes several bits. I think you forgot to rebase your changes onto master?

**Comment by cthelight** [comment]
I believe it should be fixed now. Good catch!

**Comment by bket** [comment]
BTW, how does this PR compare to #243?

**Comment by cthelight** [comment]
This PR implements a subset of the functionality of #243.

Looking at #243, It doesn't appear that you can split the output of bar_action (for example a conky script) into pieces, it seems you can only split between distinct components in the bar_format string. However, in this PR, I allow splitting in the middle of the bar_action output.

I may be mistaken, but if that is the case, the two PR's are actually quite different, and could even be used in conjunction with one another.

**Comment by cmanv** [comment]
I am the author of  #243 and you're correct: as it stands it doesn't split the output of the bar action script. However this can be fixed by moving the splitting of the text after the bar_format expansion. This will allow the use of many sections within the bar action output.

I will look into it and I'll post an update to #243

**Comment by marcopeereboom** [comment]
So should this be closed and tracked in #243?

**Comment by marcopeereboom** [comment]
#243 went in. Is this functionality part of the diff and can we close this PR?

**Comment by LordReg** [comment]
#243 is able to split bar_action when bar_action_expand is enabled, closing.

**Pull request closed without merging**
