### PR TITLE
Add -c to specify configuration file.

### LINKED ISSUE #106: Configuration file as first argument
I'd like to specify manually the path of the configuration file to read.
Since currently there's no argument parsing, I would say an optional first argument could be the file path.

Handy for debugging, mostly.

### PR DESCRIPTION
**Pull request by dajohi**
Remove references to scrotwm.conf.

Fixes #106

### CODE REVIEW

**Comment by dajohi** [comment]
totally untested :)

**Comment by LordReg** [comment]
Haven't tested yet but we need to keep those harmless scrotwm.conf checks for backwards compatibility.

**Comment by marcopeereboom** [comment]
I like the idea of having -c but when it isn't specified we need it to maintain exactly the same behavior.

**Comment by marcopeereboom** [comment]
@dajohi ?

**Comment by LordReg** [comment]
Implemented with #338

**Pull request closed without merging**
