### PR TITLE
Update spectrwm_fr.conf

### PR DESCRIPTION
**Pull request by loicreynier**
Three key bindings were not accessible with the default French keyboard.

### CODE REVIEW

**Comment by LordReg** [comment]
The changes have conflicting key bindings.

**Comment by loicreynier** [comment]
Indeed, I forgot to change the `height_shrink` bind. Corrected in last commit.

**Comment by loicreynier** [comment]
Indeed, I forgot to change the `height_shrink` key binding. Corrected in last commit.
I made a bit of mess, maybe I should create a new PR?

**Comment by LordReg** [comment]
No need to make a new PR to clean it up, you can just squash and force push.

**Comment by LordReg** [comment]
Looks good

**Pull request merged**
