### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by historical-theology**
Grammar cleanup for the front page (description)

### CODE REVIEW

**Comment by LordReg** [comment]
I like the cleanup, but I think "how hard can it be?" refers to a general development issue and wasn't meant as a comment. @marcopeereboom ?

**Comment by marcopeereboom** [comment]
It does.

**Comment by historical-theology** [comment]
@LordReg @marcopeereboom Great! It should be tidied the rest of the way now and ready to be merged. Thanks for all your hard work, including everything that went into the new (3.4.0) release :+1:

**Comment by orbea** [comment]
The grammar in this PR is wrong...

For instance you are adding a lot of arbitrary commas that should not be added.

**Pull request merged**
